"use client"

import { useState, useCallback, useEffect } from "react"
import { useQuotations } from "./use-quotations"
import { useInvoices } from "./use-invoices"
import { useFirestore } from "./useFirestore"
import { orderBy, where, doc, deleteDoc } from "firebase/firestore"
import { db } from "../lib/firebase"
import type { GSTRecord, GSTSummary, GSTReturn } from "../types/gst"

export function useGST() {
  const { data: gstRecords, loading, error, saveDocument, deleteDocument } = 
    useFirestore<GSTRecord>('gstRecords', {
      queryConstraints: [orderBy('date', 'desc')],
      includeTimestamps: true
    })
  
  const { data: gstReturns, saveDocument: saveGstReturn } = 
    useFirestore<GSTReturn>('gstReturns', {
      queryConstraints: [orderBy('period', 'desc')],
      includeTimestamps: true
    })

  const [apiError, setApiError] = useState<string | null>(null)

  const { invoices } = useInvoices()

  // Generate GST records from invoices
  const generateGSTRecords = useCallback(async () => {
    try {
      const newRecords: Omit<GSTRecord, 'id'>[] = []

      invoices.forEach((invoice) => {
        const hasExistingRecord = gstRecords.some(r => r.invoiceId === invoice.id)
        if (!hasExistingRecord && invoice.gstAmount > 0) {
          const date = new Date(invoice.createdAt)
          const month = `${date.getFullYear()}-${(date.getMonth() + 1).toString().padStart(2, "0")}`
          const quarter = `${date.getFullYear()}-Q${Math.ceil((date.getMonth() + 1) / 3)}`

          newRecords.push({
            type: "collected",
            amount: invoice.totalAmount,
            gstAmount: invoice.gstAmount, // Directly use the total GST amount from the invoice
            date: invoice.createdAt,
            month,
            quarter,
            year: date.getFullYear().toString(),
            invoiceId: invoice.id,
            description: `GST from invoice #${invoice.invoiceNumber}`,
            status: "unfiled",
            paymentStatus: invoice.paid ? "paid" : "pending",
            customerName: invoice.customerName,
            customerGSTIN: invoice.customerGSTIN || "",
          })
        }
      })

      if (newRecords.length > 0) {
        await Promise.all(newRecords.map(record => saveDocument(record)))
      }
    } catch (err) {
      console.error("Error generating GST records:", err)
      setApiError("Failed to generate GST records")
    }
  }, [invoices, gstRecords, saveDocument])

  useEffect(() => {
    if (invoices.length > 0) {
      generateGSTRecords();
    }
  }, [invoices, generateGSTRecords]);

  // Add a manual GST record
  const addGSTRecord = async (record: Omit<GSTRecord, 'id' | 'createdAt' | 'updatedAt'>): Promise<GSTRecord> => {
    try {
      // Create a new GST record with required fields
      const newRecord: Omit<GSTRecord, 'id'> = {
        ...record,
        status: 'unfiled',
        paymentStatus: 'pending',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      }
      
      // Save the document and get its ID
      const docId = await saveDocument(newRecord)
      
      // Return the complete record with the generated ID
      return {
        ...newRecord,
        id: docId
      }
    } catch (err) {
      console.error("Error adding GST record:", err)
      setApiError("Failed to add GST record")
      throw err
    }
  }

  // Update a GST record
  const updateGSTRecord = async (id: string, updates: Partial<GSTRecord>) => {
    try {
      await saveDocument({ ...updates, id } as GSTRecord)
    } catch (err) {
      console.error("Error updating GST record:", err)
      setApiError("Failed to update GST record")
      throw err
    }
  }

  // Delete a GST record
  const removeGSTRecord = async (id: string) => {
    try {
      await deleteDocument(id)
    } catch (err) {
      console.error("Error deleting GST record:", err)
      setApiError("Failed to delete GST record")
      throw err
    }
  }

  // File GST return for a period
  const fileGSTReturn = async (period: string, records: GSTRecord[], type: 'monthly' | 'quarterly') => {
    try {
      const totalGST = records.reduce((sum, record) => sum + (record.amount || 0), 0)
      const now = new Date();
      const dueDate = new Date(now.getFullYear(), now.getMonth() + 1, 20); // Assuming due date is 20th of next month

      const gstReturn: GSTReturn = {
        id: '', // Will be auto-generated by Firestore
        period,
        type,
        dueDate: dueDate.toISOString(),
        netGST: totalGST, // Simplified, assuming totalGST is the net liability
        records: records.map(r => r.id || ''),
        totalGST,
        status: 'filed',
        filedAt: now.toISOString(),
        createdAt: now.toISOString(),
        updatedAt: now.toISOString()
      }
      
      await saveGstReturn(gstReturn)
      
      // Update records to mark them as filed
      await Promise.all(
        records.map(record => 
          updateGSTRecord(record.id || '', { status: 'filed' })
        )
      )
      
      return true
    } catch (err) {
      console.error("Error filing GST return:", err)
      setApiError("Failed to file GST return")
      throw err
    }
  }

  // Update a GST return
  const updateGSTReturn = async (id: string, updates: Partial<GSTReturn>) => {
    try {
      await saveGstReturn({ ...updates, id } as GSTReturn)
    } catch (err) {
      console.error("Error updating GST return:", err)
      setApiError("Failed to update GST return")
      throw err
    }
  }

  // Get GST summary for a period (e.g., a month)
  const getGSTSummary = (month: string): GSTSummary => {
    const monthRecords = gstRecords.filter(record => record.month === month)
    
    const gstCollected = monthRecords
      .filter(r => r.type === 'collected')
      .reduce((sum, r) => sum + (r.gstAmount || 0), 0)
      
    const gstPaid = monthRecords
      .filter(r => r.type === 'paid')
      .reduce((sum, r) => sum + (r.gstAmount || 0), 0)
      
    const netGST = gstCollected - gstPaid
    
    return {
      month,
      gstCollected,
      gstPaid,
      netGST,
    }
  }

  // Get current month's GST summary
  const getCurrentMonthSummary = (): GSTSummary => {
    const now = new Date()
    const currentMonth = `${now.getFullYear()}-${(now.getMonth() + 1).toString().padStart(2, '0')}`
    return getGSTSummary(currentMonth)
  }

  // Get total GST collected
  const getTotalGSTCollected = (): number => {
    return gstRecords
      .filter(r => r.type === 'collected')
      .reduce((sum, r) => sum + (r.gstAmount || 0), 0)
  }

  // Get total GST paid
  const getTotalGSTPaid = (): number => {
    return gstRecords
      .filter(r => r.type === 'paid')
      .reduce((sum, r) => sum + (r.gstAmount || 0), 0)
  }

  // Get net GST liability
  const getNetGSTLiability = (): number => {
    return getTotalGSTCollected() - getTotalGSTPaid()
  }

  // Debug logging for loading state and data
  console.log('[useGST] Loading state:', loading);
  console.log('[useGST] GST Records count:', gstRecords?.length || 0);
  console.log('[useGST] GST Returns count:', gstReturns?.length || 0);
  console.log('[useGST] Error:', error || apiError);

  return {
    gstRecords,
    gstReturns,
    loading,
    error: error || apiError,
    addGSTRecord,
    updateGSTRecord,
    removeGSTRecord,
    fileGSTReturn,
    updateGSTReturn,
    getGSTSummary,
    getCurrentMonthSummary,
    getTotalGSTCollected,
    getTotalGSTPaid,
    getNetGSTLiability,
    generateGSTRecords
  }
}
